### ISSUE TITLE
Allow sqld graceful shutdown

### ISSUE THREAD

**Issue by george-lim** [libsql/sqld#564]
When using sqld with docker compose [as specified](https://github.com/libsql/sqld/tree/main/docker-compose), pressing Ctrl+C while the containers are running will not result in sqld gracefully shutdown. Instead, it will hang for 10 seconds until docker sends a SIGKILL.

When using bottomless, all successive runs will always start with:
```
INFO sqld::replication::primary::logger: Replication log is dirty, recovering from database file.
```

Repro steps:
1. Choose either docker compose file from [here](https://github.com/libsql/sqld/tree/main/docker-compose) and start it
2. After everything is initialized, press Ctrl+C to gracefully shut down the containers
3. Observe that `writer` and `reader` each timeout after 10 seconds, taking 20 seconds total while nginx shuts down immediately

**Comment by george-lim** [comment]
No I don't get that line when I press Ctrl+C even on the latest version 0.20.2. Perhaps it's due to my configuration here?

```
services:
  minio:
    image: minio/minio:RELEASE.2023-08-04T17-40-21Z.hotfix.04968f7ec
    command: server /data
    volumes:
      - minio_data:/data
    expose:
      - 9000
  sqld:
    image: ghcr.io/libsql/sqld:v0.20.2
    environment:
      - SQLD_NODE=standalone
      - SQLD_ENABLE_BOTTOMLESS_REPLICATION=true
      - LIBSQL_BOTTOMLESS_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - sqld_data:/var/lib/sqld
    expose:
      - 5001
      - 8080
    depends_on:
      - minio
```

<img width="1846" alt="Screenshot 2023-09-06 at 6 52 37 PM" src="https://github.com/libsql/sqld/assets/21700768/37f80ee7-e961-4001-af4e-0726df6ed9d1">
